""" modificated table sales 

Revision ID: f18a44b34f13
Revises: 23baa7db8b7a
Create Date: 2026-05-06 14:26:13.924044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18a44b34f13'
down_revision: Union[str, Sequence[str], None] = '23baa7db8b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total', sa.Float(), nullable=False))
    op.drop_column('sales', 'activo')
    op.drop_column('sales', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sales', 'total')
    # ### end Alembic commands ###
